language: objective-c
notifications:
  email: false
osx_image: xcode7.2
before_install:
  - brew update
  - brew upgrade carthage
before_script:
  - carthage bootstrap --use-submodules --no-build
script: 
  - xctool -workspace Tentacle.xcworkspace -scheme Tentacle test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=
  - xctool -workspace Tentacle.xcworkspace -scheme TentacleiOS test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=
